package:
  name: python-neutronclient
  version: "2.4.0"

source:
  fn: python-neutronclient-2.4.0.tar.gz
  url: https://pypi.python.org/packages/source/p/python-neutronclient/python-neutronclient-2.4.0.tar.gz
  md5: d4305c2ca6b93f28ec8897487d76978b
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    - neutron = neutronclient.shell:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - "pbr >=0.6,!=0.7,<1.0"
    - argparse # [py26]
    - cliff >=1.10.0,<1.11.0
    - iso8601 >=0.1.9
    - netaddr >=0.7.12
    - oslo.i18n >=1.5.0,<1.6.0
    - oslo.serialization >=1.4.0,<1.5.0
    - oslo.utils >=1.4.0,<1.5.0
    - "requests >=2.2.0,!=2.4.0"
    - python-keystoneclient >=1.1.0
    - simplejson >=2.2.0
    - six >=1.9.0
    - babel >=1.3

test:
  # Python imports
  imports:
    - neutronclient.client
  commands:
    - neutron --help
  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: Apache Software License
  summary: 'CLI and Client Library for OpenStack Networking'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
